### ISSUE TITLE
Add renderer system

### ISSUE THREAD

**Issue by r59q** [r59q/console-game#5]
Add system that takes a rendering character component and position to render them to the console.

- [x] Hook render system to game loop
    - [x] 'test' this hook by rendering a character and test it visually.
        - Maybe check using the console_engine? 
- [x] Add rendering target resource
    - [x] Test render target resource

# Task notes
- I have added a character_renderer, which needs should add targets to be renderered on each loop.
- I have added render_targets that should be emptied and refilled each loop
    - Optimization? Overwrite old targets instead of empty and refill. Might be overkill
    - Render targets should only be added to serial SystemStages i think. In order to avoid race conditions.
